## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# Allow failures on nightly julia
matrix:
 allow_failures:
 - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran

#before_script: # homebrew for mac
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask uninstall oclint; brew install gcc; fi

script:
 - julia -e 'Pkg.clone(pwd()); Pkg.build("CircStats"); Pkg.test("CircStats"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("CircStats")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
