name = "CircStats"
uuid = "0643c194-c041-11e9-0ba9-f5a9f5a21f3b"
authors = ["Andy Nowacki <a.nowacki@leeds.ac.uk>"]
version = "0.2.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"
